### ISSUE TITLE
Omni mode can't handle fast input

### ISSUE THREAD

**Issue by desiremusic** [MiguelGuthridge/Novation-LaunchKey-Mk2-Script#39]
Mostly used for hi-hats rolls, for example, you can't do them on Omni mode because when you try to press notes faster like 1/8 notes, pad turns off for a split second and don't produce any sound. I guess note on/off command reacts slowly so it cancels each other out. Maybe it is a problem with the pads themselves.

**Comment by MaddyGuthridge** [comment]
I'll investigate this. I didn't notice any issues, but I wasn't doing any complex stuff like that.

**Comment by MaddyGuthridge** [comment]
This one is probably because you're playing fast enough that you press down on the drum pad before you lift it up (which would mean that you wouldn't get a note off or note on event), meaning that my script can't do anything about it. As well as that, it sometimes won't send events because you didn't press down hard enough, which is especially likely when you're playing fast. I think this is more of a hardware limitation than an issue with the script.
